### PR TITLE
Add ipv6 and http2 support

### PR DESCRIPTION
**Pull request by nemchik**
Couldn't reopen #179 because (overwrote the branch history). This has been tested more thoroughly on ipv4. One reported user `ldsk_blitz#3042` on discord confirmed this configuration to work for him using http validation and ipv6.

### CODE REVIEW

**Comment by nemchik** [comment]
I'd like to revisit this after #198

I'll get the newer configs updated so we've got them all covered.

**Comment by nemchik** [comment]
Came across some some more info recently, http2 currently doesn't do anything for proxies. `proxy_pass` will only send http 1.1 even if the system being proxied supports http2. So http2 doesn't serve any purpose in the proxy configs unless nginx changes their stance. It could still be useful in the default site config if someone is actually using this container as a web server rather than just a proxy, but I'm not going to push for that unless there's interest.

IPv6 on the other hand does serve a purpose in both the default site config and the proxy configs. I'd like to redo this or close it and open a new PR for the purpose of only IPv6. I'll of course also make the appropriate PR to the proxy config repo given the recent changes in how this repo works.

Thoughts?

**Comment by LBegnaud** [comment]
From what i've read, http2 on the listen directive does actually provide benefit. The reasoning is that http2 benefits most for medium latency traffic. Therefore if you have nginx as a proxy for a local (to nginx) webserver, the internet traffic is getting http2 benefits while the proxied traffic is still http1, but mostly unaffected. Also keep in mind that often times the proxy_pass directive uses http. This is when we benefit the most from the above setup. http2's main benefit is that it doesn't require bringing up and tearing down TLS threads for small requests. If the client talkign to nginx gets that benefit, and the backend doesn't have a TLS layer at all, I would say we're getting a pretty good deal by enabling http2 only on the listen side.

Furthermore, if one configured nginx to cache certain subpaths, the full http2 benefits would be achieved when serving cached content.

Just my 2 cents.

**Comment by nemchik** [comment]
Just to reference some material that lead me to my previous post:

https://www.nginx.com/blog/http2-module-nginx/

> **Q:** Will you support HTTP/2 on the upstream side as well, or only support HTTP/2 on the client side?
> 
> **A:** At the moment, we only support HTTP/2 on the client side. You can’t configure HTTP/2 with [proxy_pass](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass). 

https://serverfault.com/a/765337/177096
There is some more quoted material here linking back to nginx's bug tracker and mailing list.

I do not believe it causes any harm to include as shown in the example from https://www.nginx.com/blog/nginx-1-13-9-http2-server-push/ under the heading **Automatically Pushing Resources to Clients**, but this example doesn't seem to imply any benefit to the way these proxy samples are setup if they were to include http2.

I am not opposed to more information showing otherwise, or just simply keeping the http2 listen on the proxy configs for the sake of potential future use (since they don't cause any harm) but I'm fairly sure they do not provide any benefit currently, which could lead to some confusion (hopefully it would not lead to any support requests). Maybe an ideal solution would be to leave a comment on each `listen` line that indicates that http2 currently has no effect on proxies, but is included for uniformity or something.

Thoughts?

**Comment by nemchik** [comment]
I will create the appropriate PR on the proxy repo and one for this repo as well to cover the default site-conf. Thanks.

**Pull request closed without merging**
