### PR TITLE
Add Support for Second Certificate for specified subdomains

### PR DESCRIPTION
**Pull request by brandonkal**
Rebased code to support second certificate with CERT2_SUBDOMAINS variable. I have thoroughly tested my changes and updates with a docker build (you can view my dockerhub) that is working and live on my personal unraid server.

This is my suggested pull request from earlier. I like the idea of having two different certificates on my server for a different set of subdomains.

I could not figure out how to update my pull request from earlier so that my changes could easily be seen. Doing a rebase attached myself to all 84 commits that were made since I last made the pull request. If the team has suggestions in that regard, please let me know.

I hope others will find this useful, it would be great if this could be merged as maintaining a separate branch is time consuming.

### CODE REVIEW

**Comment by sparklyballs** [comment]
"maintaining a separate branch is time consuming"

as opposed to us maintaining this rewritten script for a niche use

**Comment by popwebz** [comment]
I have no issue maintaining my changes to this script. My point was that I am not fluent enough with github at the moment keep my branch in sync with my commit appearing at the end to make it easier for you guys to see the changes in the code. As it is now, I must delete my multiple-certs branch and recreate it to keep try to make the changes readable for you guys.

**Comment by aptalca** [comment]
While we do appreciate the PR, this use case is too far outside of the scope of this image. It adds a lot of complexity for little gain.

We can leave it open here so anyone interested can build locally, but I don't feel comfortable merging and having to maintain it. The cert logic already has gotten too complicated with extra domains and such

**Comment by realies** [comment]
Please merge.

**Comment by popwebz** [comment]
As you can see from my last few commits, I attempted to smarten the script to only delete and renew the certificates that have detected changes. It ended up complicating the code too much and thus I reverted those commits. As it is now, if a change is detected for either of the two certificates, both certificates will be renewed which is a reasonable compromise considering the infrequency of domain changes. I suggest using the staging flag first to verify that the certificates are created as you wish.

**Comment by thelamer** [comment]
@aptalca We should not leave this open indefinitely. 

@brandonkal  looking over the changes and this issue I think it would be more prudent to help you get this up on Dockerhub under your own tag vs us pulling in this code. 
I agree with @aptalca the general userbase does not have this need, it is slightly niche and not something we want to support. 

If you want to hop on Discord https://discord.gg/YWrKVTn you can message me personally or our #docker-support room and we can guide you through setting up a multi arch pipeline in travis so you can make this fork public on Dockerhub. 
A basic breakdown of the commands needed here: 
https://github.com/Taisun-Docker/updater/blob/master/.travis.yml

This would all be free and allow you to consume an endpoint to fit your needs and possibly other users.

**Comment by brandonkal** [comment]
@thelamer I have since abandoned this approach long ago. I did have a separate Docker Hub build at one point. I will close now and @aptalca can open it again if desired.

**Pull request closed without merging**
