### PR TITLE
Updated ngnix

### PR DESCRIPTION
**Pull request by HenrikBacher**
Updated nginx to latest stable version

### CODE REVIEW

**Comment by nemchik** [comment]
Unfortunately that's now how this works. The file you have edited is the result of the LSIO bot recording the installed versions from the container after the package manager inside the container does what it can to install the latest versions of the software. In this case `apk` for alpine linux is used and only the latest versions of the packages available in their repositories can be used. This file does not dictate the versions used (again it just records what versions were installed by `apk` which uses the latest available in the apline repos).

**Comment by HenrikBacher** [comment]
> Unfortunately that's now how this works. The file you have edited is the result of the LSIO bot recording the installed versions from the container after the package manager inside the container does what it can to install the latest versions of the software. In this case `apk` for alpine linux is used and only the latest versions of the packages available in their repositories can be used. This file does not dictate the versions used (again it just records what versions were installed by `apk` which uses the latest available in the apline repos).

The ones based from here? https://pkgs.alpinelinux.org/packages?name=&branch=v3.9

**Comment by nemchik** [comment]
> > Unfortunately that's now how this works. The file you have edited is the result of the LSIO bot recording the installed versions from the container after the package manager inside the container does what it can to install the latest versions of the software. In this case `apk` for alpine linux is used and only the latest versions of the packages available in their repositories can be used. This file does not dictate the versions used (again it just records what versions were installed by `apk` which uses the latest available in the apline repos).
> 
> The ones based from here? https://pkgs.alpinelinux.org/packages?name=&branch=v3.9

Correct. Thus you will see https://pkgs.alpinelinux.org/packages?name=nginx&branch=v3.9 nginx matches the version present in the text file (prior to the proposed changes). As of writing that is `1.14.2-r1`.

**Comment by aptalca** [comment]
That's right. That file is only there for reference, so our CI can check to see if there are currently any updates to those packages in the upstream repo and if so, it will trigger a new docker image build

**Pull request closed without merging**
