### PR TITLE
would be appreciate if you would won't mind to add this apcu gmp and sudo to your container

### PR DESCRIPTION
**Pull request by JOduMonT**
add php7-apcu php7-gmp and sudo

### CODE REVIEW

**Comment by j0nnymoe** [comment]
You've ignored the questions in the PR template. Please fill these in.

**Comment by JOduMonT** [comment]
Description: docker-letsencrypt image with php7-apcu php7-gmp and sudo
Benefits of this PR and context: 
- sudo: able to run cron as a user
- php7-apcu: apcu is the new version of APC cache which help a lot PHP to perform well
- php-gpm: gpm is a library used to manipulate image 
How Has This Been Tested?
by script, by hand, by dockerfile, by me ???
Source / References: https://github.com/linuxserver/docker-letsencrypt/pull/376/files

**Comment by thelamer** [comment]
Conventionally we use : 
```
s6-setuidgid abc YOURCOMMANDHERE
```
Have you tried this S6 wrapper for your scripts that run as other users ? (abc should be the only user you ever use in the container)

**Comment by JOduMonT** [comment]
@thelamer no I did'nt because I was inspired by https://github.com/linuxserver/docker-nextcloud/blob/master/Dockerfile#L62

**Comment by JOduMonT** [comment]
sorry I don't understand your PR process
why it's invalid ?

@thelamer why the convention is not followed in https://github.com/linuxserver/docker-nextcloud/blob/master/root/etc/services.d/cron/run

**Comment by aptalca** [comment]
It was marked invalid for 2 reasons:
1. The PR template was not filled in and no info was provided
2. Changes made only to the x86 Dockerfile

What convention are you referring to?

**Comment by JOduMonT** [comment]
@aptalca thanks for your reply
1. after @j0nnymoe I filled the PR template as far as I able
YES of course, my PR is not multi-arch (I forget this part)

2. I was refering to @thelamer comment which

> Conventionally we use :
> 
> ```
> s6-setuidgid abc YOURCOMMANDHERE
> ```

anyway I'll fork it it will be simplier for everyone :)

**Comment by aptalca** [comment]
What you linked to is the `service` file that starts the cron service. What thelamer referred to is the script that is run by cron. If you let us know what exactly you're trying to accomplish, we can better help you.

**Comment by JOduMonT** [comment]
> we can better help you.

I use letsencrypt as host for several php apps such as nextcloud, wordpress, ...
for an example nextcloud require a cron as the user
this is why I added sudo

**Comment by LBegnaud** [comment]
imo you should be running that in a separate container. Leave this as an nginx reverse proxy.

**Comment by JOduMonT** [comment]
@LBegnaud  I understand your point of view
but why in that case integrating PHP in this image ?

**Comment by LBegnaud** [comment]
I would honestly prefer they didn't, but at the end of the day it doesn't affect the performance and reliability of my using it as an nginx proxy container. I trust the maintainers to balance ease of use with security/performance/reliability, so I just chime in every now and then to share my desires 8)

**Comment by JOduMonT** [comment]
@LBegnaud at the end if I really die for it I just have to build an IMAGE FROM it :)

**Pull request closed without merging**
