### PR TITLE
Enable Second Certificate

### PR DESCRIPTION
**Pull request by popwebz**
I made some changes so that I could maintain two separate certificates for a different set of subdomains. Perhaps some others would like to do the same. This code will only create a second certificate if:
1. only use subdomains is true
2. CERT2_SUBDOMAINS contains a list

### CODE REVIEW

**Comment by realies** [comment]
Great to see multi-domain with separate certificates support, hope to see this merged soon.

**Comment by nalt** [comment]
Great! The general use-case would be multiple certificates, not just two, I guess. Would it be hard to extend?

**Comment by popwebz** [comment]
My changes could be repeated for more certificates, but the number would be finite. Adding more is not something I'm looking for but someone could extend it to 3 or 4 certificates etc.

**Comment by popwebz** [comment]
Updated to be in sync with changes. Should be able to merge now

**Comment by popwebz** [comment]
This is no longer working with the recent linuxserver commits. I am going to close this and start a new pull request.

**Pull request closed without merging**
