### PR TITLE
Update proxy confs

### PR DESCRIPTION
**Pull request by aptalca**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by aptalca** [comment]
jenkins test this please

**Comment by aptalca** [comment]
jenkins test this please

**Comment by aptalca** [comment]
jenkins test this please

**Comment by thelamer** [comment]
jenkins test this please

**Comment by aptalca** [comment]
jenkins test this please

**Comment by aptalca** [comment]
jenkins errors I can't figure out

**Pull request closed without merging**
