### PR TITLE
Add propagation parameter for dns validation, add whois

### LINKED ISSUE #151: fail2ban issue with f2b-nginx-http-auth jail not blocking
IPs getting not blocked on authentication errors from nginx auth jail

Host OS: QNAP QTS 4.34.0644

2018-08-08 11:23:25,025 fail2ban.filter         [337]: INFO    [nginx-http-auth] Found 188.192.9.2 - 2018-08-08 11:23:24
2018-08-08 11:23:42,241 fail2ban.filter         [337]: INFO    [nginx-http-auth] Found 188.192.9.2 - 2018-08-08 11:23:41
2018-08-08 11:23:43,443 fail2ban.filter         [337]: INFO    [nginx-http-auth] Found 188.192.9.2 - 2018-08-08 11:23:43
2018-08-08 11:23:44,044 fail2ban.filter         [337]: INFO    [nginx-http-auth] Found 188.192.9.2 - 2018-08-08 11:23:43
2018-08-08 11:23:45,245 fail2ban.filter         [337]: INFO    [nginx-http-auth] Found 188.192.9.2 - 2018-08-08 11:23:44
2018-08-08 11:23:45,252 fail2ban.actions        [337]: NOTICE  [nginx-http-auth] Ban 188.192.9.2
2018-08-08 11:23:45,257 fail2ban.utils          [337]: Level 39 7f16c963e8c8 -- exec: iptables -w -N f2b-nginx-http-auth
iptables -w -A f2b-nginx-http-auth -j RETURN
iptables -w -I INPUT -p tcp -m multiport --dports http,https -j f2b-nginx-http-auth
2018-08-08 11:23:45,257 fail2ban.utils          [337]: ERROR   7f16c963e8c8 -- stderr: 'iptables: Chain already exists.'
2018-08-08 11:23:45,257 fail2ban.utils          [337]: ERROR   7f16c963e8c8 -- stderr: 'iptables: No chain/target/match by that name.'
2018-08-08 11:23:45,258 fail2ban.utils          [337]: ERROR   7f16c963e8c8 -- returned 1
2018-08-08 11:23:45,258 fail2ban.actions        [337]: ERROR   Failed to execute ban jail 'nginx-http-auth' action 'iptables-multiport' info 'ActionInfo({'ipfailures': 22, 'ip-rev': '2.9.192.188.', 'family': 'inet4', 'ipmatches': '188.192.9.2.........

### LINKED ISSUE #427: transip dns validation mostly broken
## Expected Behavior
Requesting a certificate for a TransIP domain via the transip dns plugin would work.

## Current Behavior
Requesting a certificate for a TransIP domain via the transip dns plugin fails most of the time. I have seen it succeed once, and fail many times.

## Command used to create docker container (compose)
``` yaml
  letsencrypt:
    image: linuxserver/letsencrypt
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/London
      - URL=example.com
      - VALIDATION=dns
      - DNSPLUGIN=transip
    volumes:
      - ./transip/transip.ini:/config/dns-conf/transip.ini
      - ./transip/private-key-rsa.pem:/config/dns-conf/private-key-rsa.pem
```

## Docker logs
```
letsencrypt_1         | Obtaining a new certificate
letsencrypt_1         | Performing the following challenges:
letsencrypt_1         | dns-01 challenge for example.com
letsencrypt_1         | Unsafe permissions on credentials configuration file: /config/dns-conf/transip.ini
letsencrypt_1         | Successfully added TXT record
letsencrypt_1         | Waiting 180 seconds for DNS changes to propagate
letsencrypt_1         | Waiting for verification...
letsencrypt_1         | Challenge failed for domain example.com
letsencrypt_1         | dns-01 challenge for example.com
letsencrypt_1         | Cleaning up challenges
letsencrypt_1         | Removing TXT record with name: _acme-challenge
letsencrypt_1         | Some challenges have failed.
letsencrypt_1         | IMPORTANT NOTES:
letsencrypt_1         |  - The following errors were reported by the server:
letsencrypt_1         |
letsencrypt_1         |    Domain: example.com
letsencrypt_1         |    Type:   unauthorized
letsencrypt_1         |    Detail: No TXT record found at _acme-challenge.example.com
letsencrypt_1         |
letsencrypt_1         |    To fix these errors, please make sure that your domain name was
letsencrypt_1         |    entered correctly and the DNS A/AAAA record(s) for that domain
letsencrypt_1         |    contain(s) the right IP address.
letsencrypt_1         |  - Your account credentials have been saved in your Certbot
letsencrypt_1         |    configuration directory at /etc/letsencrypt. You should make a
letsencrypt_1         |    secure backup of this folder now. This configuration directory will
letsencrypt_1         |    also contain certificates and private keys obtained by Certbot so
letsencrypt_1         |    making regular backups of this folder is ideal.
letsencrypt_1         | ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/transip.ini file.
```

## Expected cause
Currently the dns propagation time [is hardcoded to 180 seconds](https://github.com/linuxserver/docker-letsencrypt/blob/6d2b223b80a3a9436a110549f8657029ffc62491/root/etc/cont-init.d/50-config#L184). For the transip certbot plugin [the default is 240](https://github.com/hsmade/certbot-dns-transip/blob/8a59a1df6550b2bd0c4bf379ee7adf6a3b42ed3d/certbot_dns_transip/dns_transip.py#L48), so the hardcoded value is *lower* than the plugins' default. I have seen someone mention in an issue that even the default of 240 is sometimes not long enough.

So TransIP seems to be slow with propagating changes, and the hardcoded value of 180 is not enough.

## Proposed fix
Use an environment variable for the propagation time, with a default of 180. Alternatively increase the hardcoded value to 240 or higher.

### LINKED ISSUE #442: Whois can't handle IP Addresses
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

sudo docker exec -it letsencrypt /usr/bin/whois 107.33.23.17 should produce Whois information both on the command line and in notifications

## Current Behavior

sudo docker exec -it letsencrypt /usr/bin whois 107.33.23.17 produces:
[Querying whois.iana.org:43 '107.33.23.17']
[Querying whois.iana.org:43 'domain 107.33.23.17 ']
[whois.iana.org]
% IANA WHOIS server
% for more information on IANA, visit http://www.iana.org
%
% Error: Invalid query domain 107.33.23.17 
but sudo docker exec -it letsencrypt /usr/bin whois google.com produces expected results

Also, on my system, /usr/bin/whois 107.33.23.17 produces the expected results

It seems that the whois client on my docker host supports querying by ip-address, but the whois binary inside the 'letsencrypt' docker container doesn't.  It seems as if the whois client inside the docker only queries domains even though the action.d is setup to query IP addresses.

## Steps to Reproduce

1. sudo docker exec -it letsencrypt /usr/bin whois 107.33.23.17
2.
3.
4.

## Environment
**OS:**      
Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-99-generic x86_64)

**CPU architecture:** x86_64/arm32/arm64
x86_64      
**How docker service was installed:**
      

version: "2" 
services:
  letsencrypt: # https://github.com/linuxserver/docker-letsencrypt
    container_name: letsencrypt
    image: linuxserver/letsencrypt:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - /home/user/docker/letsencrypt/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=xxxx
      - PUID=xxxx
      - EMAIL=my_email@gmail.com
      - URL=myduckdns.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - TZ=America/New_york
      - DUCKDNSTOKEN=myxxxxxduckdnsxxxxxtoken
    ports:
      - "80:80"
      - "443:443"

## Command used to create docker container (run/create/compose/screenshot)

Docker Compose

### PR DESCRIPTION
**Pull request by aptalca**
- Add propagation parameter for dns validation
- Add whois from repo (to replace busybox version)
- Force renewal after changing duckdns token
- Blank out optional param values
- Change fail2ban default ban action to `iptables-allports`, which seems to be more widely supported

closes #442 
closes #427 
closes #428 
closes #151 

~~Awaiting user testing and feedback~~ user confirmed working with transip

### CODE REVIEW

**Comment by marklagendijk** [comment]
@aptalca I just tried with TransIP. I get the following error:
```
certbot: error: ambiguous option: --certbot-dns-transip=dns-transip-propagation-seconds 300 could match --certbot-dns-transip:dns-transip-propagation-seconds, --certbot-dns-transip:dns-transip-credentials
```

**Comment by aptalca** [comment]
@marklagendijk did you remember to remove the propagation setting from your ini file? Because your error shows the parameter with a `=` but the new code has `:`

**Comment by marklagendijk** [comment]
Good catch! That was indeed the issue. Will try again.

**Comment by marklagendijk** [comment]
@aptalca when I removed the setting from the ini file it worked. I was able to successfully create a certificate, including wildcard.

Thanks for implementing this! 👍

**Pull request merged**
