### PR TITLE
Move php conf to separate file

### PR DESCRIPTION
**Pull request by nemchik**
This ties to #174 
I have moved the php conf to a separate file and included that file inside the `/` location. Any other location that needs php can easily include the same file. This should negate the need to comment out the php conf when using rutorrent.

### CODE REVIEW

**Comment by nemchik** [comment]
As a side note, it is possible that people may have configured locations that rely on the php conf and not accounted for this change. None of the examples included in the container would be affected by this, but for any end user that would be they can simply add the `include /config/nginx/php.conf;` line to the affected location.

**Comment by aptalca** [comment]
I've been meaning to rework the php block so I'll have to give this more thought

**Comment by nemchik** [comment]
I added an extra line to this (the try_files) per the recommendation in nginx docs (link in the commit message). aside from that they really don't have any recommendations to improve php in nginx any more than what you already have.

The only difference that I've found that could MAYBE be a positive would be switching from the TCP to the socket FPM which eliminates the network stack from the process but it's considered negligible for use cases like this in docker.

I still stand by moving PHP conf into a file that can be easily included in other location blocks and not having it in the main server block (rather have it by default in the `/` location) seems to be the most universal solution that solves the conflict with rutorrent without breaking any of the other configs.

P.S. I even dug through the base image to find where you were setting the fastcgi_param and there's no better recommendation than what you have for that either. (at least that I could find)

**Comment by nemchik** [comment]
I've rebased this to master to accommodate 7400c4a098d0f0adc37c86a274acd4679f4ad9d1

**Comment by aptalca** [comment]
I decided to keep the php block in there. It's only a few lines and since it's not expected to be reused in proxy confs, there isn't too much benefit to separating it out.

If one needs to reuse it in a lot of server and/or location blocks, they can separate it out themselves.

**Pull request closed without merging**
