### PR TITLE
Give Digital Ocean a longer propagation time

### PR DESCRIPTION
**Pull request by Jleagle**
I have given digital ocean a 2 minute propagation time.

My script was continuously failing because of "Incorrect TXT record", the TXT record it found in the log was always the previous value of the txt record. After updating the record, it seemed to check too quickly and get the previous instead of new value.

After setting it to two minutes, it has worked every time.

### CODE REVIEW

**Comment by nemchik** [comment]
I wonder if we should just make an environment variable with a default value for this. then you could increase that timeout for any dns provider and you could set your own limit individually.

**Comment by Jleagle** [comment]
#125

**Comment by nemchik** [comment]
Good find! Two things to note here:

The OP of that issue mentioned you can create a file in your config directory for the container `/config/etc/letsencrypt/cli.ini` with the contents
```
dns-<plugin>-propagation-seconds 300
```
(from their example - in your case 120 seconds sounds like it would do the trick)
and this should fully and permanently resolve your issue.

That does not negate that an environment variable may be easier for end users, but we're not seeing lots of reports of this issue, so it may be better that we just include mention of that file in our docs and provide a basic example or link to further documentation upstream.

**Comment by nemchik** [comment]
P.S. would you be willing to create that file and see if it actually does solve your issue just to confirm for you specifically?

**Comment by aptalca** [comment]
I'm not in favor of setting different options for each dns provider.
I do not like changing the default values because the last time I did, it broke another provider. See my reply here: https://github.com/linuxserver/docker-letsencrypt/issues/427#issuecomment-606825786

**Comment by marklagendijk** [comment]
I have tried the cli.ini approach, but it does not work.
The issue is that the correct config for transip would be:
```
certbot-dns-transip:dns-transip-propagation-seconds 300
```
However, certbot does not support the `:` in a ini file (it sees it as `=`). There [is a pull request on certbot](https://github.com/certbot/certbot/pull/7026) for this, but this has been open for a long time.

**Comment by allanesquina** [comment]
Hi guys, I'm facing the same problem here using `certbot-dns-digitalocean`.
I can see the records when I update my D.O panel but I get validation error in dns challenge. The timeout of 10s may be the problem.

**Comment by aptalca** [comment]
@allanesquina @Jleagle @marklagendijk 

Can you guys give this PR a try? https://github.com/linuxserver/docker-letsencrypt/pull/444

There is a new env var called `PROPAGATION` and you set it to a number (seconds)

Just replace the image `linuxserver/letsencrypt` with the following to test:
`lspipepr/letsencrypt:1.3.0-pkg-0aa80b10-pr-444`

Let us know which dns plugin you used.

Thanks

**Pull request closed without merging**
