### PR TITLE
Add nextcloud subfolder config

### PR DESCRIPTION
**Pull request by LeoVerto**
Instructions for what to add to the nextcloud config are included as a comment.

I've tested this setup myself and haven't run into any problems so far.

### CODE REVIEW

**Comment by aptalca** [comment]
Thanks, this was an elusive one. 

I'll get a couple team members to test it before merging

**Comment by aptalca** [comment]
@LeoVerto I just realized that this hardcodes the container name, which is not ideal, because if nextcloud is down, nginx won't start

If I use the variable setting hack as with other proxy confs, the rewrite messes that up. Can you figure out a way around that?

Thanks

**Comment by nemchik** [comment]
I don't have nextcloud handy but maybe it would be
```
location /nextcloud {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_nextcloud nextcloud;
    rewrite /nextcloud(.*) $1 break;
    proxy_pass http://$upstream_nextcloud:443;
}
```
This seems to work for plex and for rutorrent. a 301 redirect may be needed to force a trailing slash.

**Comment by aptalca** [comment]
Thanks @nemchik the following seems to work

```
# Assuming this container is called "letsencrypt", edit your nextcloud container's config
# located at /config/www/nextcloud/config/config.php and add the following lines before the ");":
#  'trusted_proxies' => ['letsencrypt'],
#  'overwritewebroot' => '/nextcloud',
#  'overwrite.cli.url' => 'https://your-domain.com/nextcloud',
#
# Also don't forget to add your domain name to the trusted domains array. It should look somewhat like this:
#  array (
#    0 => '192.168.0.1:444', # This line may look different on your setup, don't modify it.
#    1 => 'your-domain.com',
#  ),

# Redirects for DAV clients
location = /.well-known/carddav {
    return 301 $scheme://$host/nextcloud/remote.php/dav;
}

location = /.well-known/caldav {
    return 301 $scheme://$host/nextcloud/remote.php/dav;
}

location /nextcloud {
    return 301 $scheme://$host/nextcloud/;
}

location /nextcloud/ {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_nextcloud nextcloud;
    rewrite /nextcloud(.*) $1 break;
    proxy_pass https://$upstream_nextcloud:443;
    
    proxy_max_temp_file_size 2048m;

    proxy_set_header Range $http_range;
    proxy_set_header If-Range $http_if_range;
    proxy_set_header Connection $http_connection;
    proxy_redirect off;
    proxy_ssl_session_reuse off;
}
```

**Comment by LeoVerto** [comment]
Ah yeah, that one I wasn't able to crack.

@aptalca just a minor note, by changing the location and rewrite regexes like this https://site.com/nextcloud (without a trailing slash) won't redirect properly.

**Comment by aptalca** [comment]
Another issue with the config

With the reverse proxy, uploads don't work due to nextcloud assuming free space is 0.

Here's what I found so far. Prior to an upload, nextcloud checks the quota and free space via GET to `/index.php/apps/files/ajax/getstoragestats.php?dir=%2F`, which returns:
`{"data":{"uploadMaxFilesize":535822336,"maxHumanFilesize":"Upload (max. 511 MB)","freeSpace":8021061632,"quota":-3,"used":7465217,"usedSpacePercent":0,"owner":"admin","ownerDisplayName":"admin"},"status":"success"}`

But with the reverse proxy, the GET to `/nextcloud/index.php/apps/files/ajax/getstoragestats.php?dir=%2F` results in an error, and nc assumes no free space

Any ideas how to fix that?

**Comment by aptalca** [comment]
Here's the specific error from letsencrypt's nginx log:
[error] 373#373: *860 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: XXXXXXXXX, server: _, request: "GET /nextcloud/index.php/apps/ajax/getstoragestats.php?dir=%2F HTTP/1.1"

**Comment by LeoVerto** [comment]
Hmm, that looks like the `location` tag didn't kick in correctly and the letsencrypt container tried to handle the request on it's own which obviously failed due to the file not existing in its FS.

**Comment by nemchik** [comment]
Curious @aptalca if you have the php block in `default` commented out?

**Comment by aptalca** [comment]
doh, you're right, I didn't realize myself that I was looking at the letsencrypt log lol

changing location to `location ^~ /nextcloud/` took care of it

**Comment by aptalca** [comment]
@nemchik no, it's not. I try to test everything with default conf + minimum customization

**Pull request merged**
