### PR TITLE
Update fail2ban defaults in /config

### PR DESCRIPTION
**Pull request by aptalca**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by aptalca** [comment]
Don't merge yet, need to test

**Comment by aptalca** [comment]
Jenkins please test this again

**Comment by aptalca** [comment]
jenkins, don't make me angry; just retest this

**Comment by sparklyballs** [comment]
please test this

**Comment by sparklyballs** [comment]
test this please

**Comment by aptalca** [comment]
This is ready for merge

**Comment by sparklyballs** [comment]
reference #49

**Pull request merged**
