### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by CHBMB**
Closes https://github.com/linuxserver/docker-letsencrypt/issues/505

### CODE REVIEW

**Comment by CHBMB** [comment]
@aptalca I haven't read the contributing guideline either. My bad.
Do we need to apply the change to readme-vars.yml given this is deprecated?

**Comment by nemchik** [comment]
Yeah this should be done in the vars.

**Comment by aptalca** [comment]
Actually don't bother with this one. When we got the trademark related request, we changed all references to letsencrypt to swag in the readme. So technically, the whole thing is wrong. In other words, the link is correct, but the link text is wrong. I'd just leave it as is since it's already deprecated and there is proper info on the new repo up top.

**Comment by CHBMB** [comment]
No worries.

**Pull request closed without merging**
