### PR TITLE
adds php7-pgsql

### PR DESCRIPTION
**Pull request by realies**
#133

### CODE REVIEW

**Comment by realies** [comment]
@LinuxServer-CI, that can be automated.

**Comment by sparklyballs** [comment]
we know but we're not gonna leave ourselves open to someone malicious flooding our build servers with bogus PR's etc

**Comment by realies** [comment]
There's various ways to limit being maliciously flooded. Since this is open-source, Travis-CI wouldn't mind building for free.

**Comment by aptalca** [comment]
Jenkins test this please

**Pull request merged**
