### PR TITLE
Removes TLSv1 from default ssl.conf

### PR DESCRIPTION
**Pull request by Kritner**
TLSv1 is no longer considered secure, the end of life was on June 30, 2018.
This PR removes TLSv1 as a default in ssl.conf - will assist with an easier time for getting an A+ rating from websites such as ssllabs.com.

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by aptalca** [comment]
I have mixed feelings about this. Technically, tlsv1.1 is also end of life. However, I'm not aware of a critical vulnerability in either 1.0 or 1.1 so for compatibility, I'm inclined to keep them in for now.

Plus, ssl.conf is user configurable so anyone can edit that however they wish

**Comment by Kritner** [comment]
No problem, feel free to close, it was just one of the only things preventing a default of a+ rating from ssl labs.

And ah, didn't realize 1.1 was also eol, surprising that didn't count against my score

**Comment by nemchik** [comment]
I'm inclined to suggest using settings close to one of these two configs

https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=nginx-2.4.7&openssl=1.0.1e&hsts=yes&profile=modern (more strict)

https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=nginx-1.14.0&openssl=1.0.1e&hsts=yes&profile=intermediate (less strict)

Both list which browsers are supported. Maybe we just include the intermediate by default and the strict as comments? I think the configs in this repo are already pretty close to intermediate.

Intermediate is plenty to get an A+ on ssllabs and I'm pretty sure securityheaders.io as well. Mozilla observatory gives it a B.

**Comment by Kritner** [comment]
@nemchik updated, just curious as to the reasoning behind not having it enabled?  If the purpose of this image is to get your site up and running with a valid cert, wouldn't it make sense to use HSTS? Though I guess port 80 is disabled on the default.conf anyway.

**Comment by nemchik** [comment]
The reason I feel it should not be enabled by default is it is a bit of a commitment for the end user to have it enabled. Once enabled it sets up an expiration that keeps it active for the defined period of time even if you disable it on the server end. Individuals can forcefully clear their systems from remembering the header, but it's not a straightforward process and needs to be done on each browser the site was visited in (meaning all the visitors of the site).

During initial setup some users might make adjustments to their setup and not be ready for the commitment mentioned above. When someone first sets their system up if they make a mistake and need to adjust things it's better to get those adjustments out of the way before setting a forced use of https.

Also some users might want to actually use http (to which I would say there are other containers for that).

**Comment by aptalca** [comment]
HSTS is a sledgehammer. Once it is cached by a browser, it will refuse any non-https request or invalid https request for the entire domain and subdomains (with subdomains enabled). It's good for a production environment, but can be a nightmare for a home user who is trying to set up a bunch of services through trial and error.

So we like to keep it off by default and when the user completes the setup of their environment, they can easily enable it and register it in the global database https://hstspreload.org/

**Comment by aptalca** [comment]
I'm going to close this because I'm in favor of keeping TLS 1 and 1.1 for the moment

**Comment by nemchik** [comment]
This topic has been in some relatively large news circles again https://arstechnica.com/gadgets/2018/10/browser-vendors-unite-to-end-support-for-20-year-old-tls-1-0/ seemingly with more significant impact this time (not just Microsoft). Based on the usage numbers (1%) and the announcements from multiple browser vendors I think this is worth revisiting.

#180 relates as apparently http2 requires TLS 1.2, although it seems having 1.0/1.1 enabled doesn't prevent the ability to use http2 when a connection over 1.2 it's supported.

**Comment by aptalca** [comment]
I realize the original branch is deleted so we can't reopen this, but in light of the new announcements that major browsers are getting ready to drop support for older TLS releases in the coming weeks/months, we'll do the same when we restructure this image and switch to multi-arch

**Pull request closed without merging**
