### PR TITLE
Remove references to tls-sni as it is no longer supported by LE

### PR DESCRIPTION
**Pull request by jchonig**
Addresses https://github.com/linuxserver/docker-letsencrypt/issues/389

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

 

------------------------------

We welcome all PR’s though this doesn’t guarantee it will be accepted.

### CODE REVIEW

**Comment by VijaySidhu** [comment]
It will be helpful if you guys can add youtube video tutorial about.
1.  How to use this docker image and serve static content ?
2.  How to Configure an app other than Port 80 (Used for HTTP Validation)

**Comment by CHBMB** [comment]
> It will be helpful if you guys can add youtube video tutorial about.
> 
>     1. How to use this docker image and serve static content ?
> 
>     2. How to Configure an app other than Port 80 (Used for HTTP Validation)

This is a support request you're asking for, nothing to do with this PR.  Please keep support to the channels provided.

**Comment by CHBMB** [comment]
@jchonig  Regarding the PR, LGTM, but I'm going to leave this to @aptalca as this is very much his baby.  IIRC it was left it as it was unclear at the time we discussed it whether it might be re-added as an option at some point.

**Comment by jchonig** [comment]
> @jchonig Regarding the PR, LGTM, but I'm going to leave this to @aptalca as this is very much his baby. IIRC it was left it as it was unclear at the time we discussed it whether it might be re-added as an option at some point.

If there is a chance of it coming back I suggest that the documents at least specify that it currently isn't supported.  I spent some time trying it before figuring out that it was no longer supported.

Thanks.

Jeff

**Comment by aptalca** [comment]
@jchonig 
Thanks for the PR, but it needed a rebase, and some other changes, I just committed in a separate PR

**Comment by jchonig** [comment]
No worries.

Thanks for addressing this.

Jeff

-- 
Jeffrey C. Honig <jch@honig.net>
http://jch.honig.net
PGP ID: A96C148E8B0E5F741A90ED04BBE5FFC5E52718CE
<https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xa96c148e8b0e5f741a90ed04bbe5ffc5e52718ce>
Keybase: jchonig <https://keybase.io/jchonig>
Secure E-mail <https://protonmail.com>: jchonig@pm.me

**Pull request closed without merging**
